### ISSUE TITLE
energy_predictions.yaml | entity duplicate

### ISSUE THREAD

**Issue by Symbiot78** [dykandDK/home-assistant-config#1]
Hey

As promised.

in energy_prediction.yaml on GH you are showing carnot & nordpool but you're referencing the same entity twice. (sensor.elpriser_excl_afgifter)

furthermore you reference nordpool which is configured to show inclusive of VAT but 'grønnere elforbrug' and carnot (which is energi data service as far as i can tell) are both without VAT etc.

another thing.. how are you getting nordpool & EDS/carnot to show data from today & tomorrow.. for me it shows as attached image.
I've added EDS with VAT which is why 'grønnere ..' is quite different in the chart.

Why have you decided to show without VAT etc?

![image](https://github.com/dykandDK/home-assistant-config/assets/3314249/a6834cbc-e4ea-463b-9e76-3efd1f807d50)

**Comment by dykandDK** [comment]
Thank you for identifying the issue.

The `energy_predictions.yaml` file has now been updated to remove VAT from Nordpool (was only removed for tomorrow). I have decided to show prices without VAT to make it easier to compare against, e.g. Nordpool or other sources. 

I also import the 1 year fixed price from EWII and the long term energy trading prices from EnergiDanmark. Those have now been added as well. However, NodeRED is used to collect data and generate sensors.

I also do this with Grønnere Elforbrug and Carnot which is why I have data for today and tomorrow as well...
